version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    command: rabbitmq-server
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - singlenetwork
  
  rmq_mt-publisher:
    build:
      context: .
      dockerfile: DockerfilePublisher
    container_name: rmq_mt-publisher
    depends_on:
      - rabbitmq
    networks:
      - singlenetwork
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001

  rmq_mt-consumer:
    build:
      context: .
      dockerfile: DockerfileConsumer
    container_name: rmq_mt-consumer
    depends_on:
      - rabbitmq
    networks:
      - singlenetwork
    ports:
      - 6001:6001

networks:
  singlenetwork: